before_build:  
  - restore_packages.bat

configuration: Release

on_success:
  - nuget pack Nancy.RDF.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - ps: Push-AppveyorArtifact "Nancy.RDF.$($env:APPVEYOR_BUILD_VERSION).nupkg"
